language: node_js
node_js: "15"

stages:
  - test

jobs:
  include:
    - stage: test
      name: "Test and compile"
      install:
        - npm install
      script:
        - npm test
      after_script:
        - npm run bundle:aws
        - npm run bundle:server
