sudo: required
language: node_js
node_js: "10"

services:
  - "docker"

stages:
  - test
  - push

jobs:
  include:
    - stage: test
      name: "Unit tests"
      install:
        - npm install
      script:
        - npm test

    - stage: push
      name: "Push to registry"
      if: tag IS present
