---

title:       "GitLab Status Notification"
fallback:    "GitLab Status Notification"
color:       "{{pipe.status.color}}"
pretext:     "{{pipe.status.icon}} Pipeline <{{pipe.url}}|#{{pipe.id}}> has *{{pipe.status.text}}* for project <{{proj.url}}|{{proj.name}}>:"
text:        "Pipeline has finished in {{pipe.duration}} seconds and {{decor.stage_status}}"
author_name: "{{user.name}}"
author_link: "{{user.url}}"
author_icon: "{{user.avatar}}"

fields:
  - title: Stages
    value: "{{pipe.stages.repr}}"
    short: false

  - title: Project
    value: "<{{proj.url}}|{{proj.name}}>"
    short: true

  - title: Branch
    value: "<{{proj.branch.url}}|{{proj.branch.name}}>"
    short: true

  - title: Last commit
    value: "```{{commit.message}}```"
    short: false

  - title: Commit author
    value: "`{{commit.author}} <{{commit.email}}>`"
    short: false

footer: Gitlab-CI
footer_icon: https://about.gitlab.com/images/ci/gitlab-ci-cd-logo_2x.png
ts: "{{pipe.finish}}"
