---

vars:
  - &master  "hook"
  - &staging "hook"
  - &dev     "hook"

  - &pipe
    notify: true
    template: pipeline

  - &mr
    notify: true
    template: merge

event:
  pipeline:
    success: *pipe
    failed:  *pipe
  merge_request:
    opened: *mr
    merged: *mr

notification:
  rule:
    branch:
      master:
        - *master
        - *dev
      staging:
        - *staging
      dev:
        - *dev
