---

vars:
  - &master  "hook"
  - &staging "hook"
  - &dev     "hook"

  - &pipe
    notify: true
    template: pipeline

  - &mr
    notify: true
    template: merge

event:
  pipeline:
    success: *pipe
    failed:  *pipe
  merge_request:
    opened: *mr
    merged: *mr

notification:
  branch:
    master:
      - *master
      - *dev
    staging:
      - *master
      - *dev
      - *staging
    dev:
      - *dev
