---

event:
  pipeline:
    success:
      notify: true
      template: pipeline
    failed:
      notify: true
      template: pipeline
  merge_request:
    opened:
      notify: true
      template: merge
    merged:
      notify: true
      template: merge

slack:
  master:
    hook: "hook1"
  staging:
    hook: "hook2"
  dev:
    hook: "hook3"

notification:
  rule:
    branch:
      master:
        - master
        - dev
      staging:
        - staging
      dev:
        - dev
